/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usebatchupdateinjdbc_j2.s.p0117;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhongFPT
 */
public class TheView extends javax.swing.JFrame {

    /**
     * Creates new form TheView
     */
    public TheView() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStocks = new javax.swing.JTable();
        btInsert = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbStocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Stock one", "HN", "15/02/1999", null},
                { new Integer(2), "Stoke two", "HCM", "20/06/2020", null},
                { new Integer(3), "Stoke three", "SG", "17/02/1987", "Dangrous"},
                { new Integer(4), "Stoke foure", "DN", "25/06/2001", null},
                { new Integer(5), "Stoke five", "NT", "17/02/2011", null}
            },
            new String [] {
                "StockID", "StockName", "Address", "DateAvailable", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbStocks.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tbStocks);

        btInsert.setText("Insert to DB");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInsert))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btInsert)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String convertDateFormat(String date) {
        String[] dateArray = date.split("/");
        return dateArray[2] + "/" + dateArray[1] + "/" + dateArray[0];
        
    }
    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
            try {
            // TODO add your handling code here:
                tbStocks.clearSelection();
            Connection conn = new DBContext().getConnection();
            conn.setAutoCommit(false);
            Statement st = conn.createStatement();
            st.executeUpdate("delete Stocks");
            String sql = "insert into Stocks values (?,?,?,?,?)";
            PreparedStatement pstm = conn.prepareStatement(sql);
            
            for (int i = 0; i < tbStocks.getRowCount(); i++) {
                try {
                   pstm.setInt(1, (int) tbStocks.getValueAt(i, 0)); 
                } catch (Exception e) {
                    int id = Integer.parseInt((String)tbStocks.getValueAt(i, 0));
                    pstm.setInt(1, id); 
                }
                
                
                pstm.setString(2, (String) tbStocks.getValueAt(i, 1));
                pstm.setString(3, (String) tbStocks.getValueAt(i, 2));
                String date = (String) tbStocks.getValueAt(i, 3);
                if (date.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}")) {
                    date = convertDateFormat(date);
                }        
                pstm.setString(4, date);
                pstm.setString(5, (String) tbStocks.getValueAt(i, 4));
                
                pstm.addBatch();
            }
            
            pstm.executeBatch();
            conn.commit();
            JOptionPane.showMessageDialog(rootPane, "InsertSuccessful");
            pstm.clearBatch();
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TheView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btInsertActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInsert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbStocks;
    // End of variables declaration//GEN-END:variables

   
}
